### ISSUE TITLE
Ability to Kill 2 way comm (to reduce unnecessary cpu usage)

### ISSUE THREAD

**Issue by htcohio** [user1321/wifibroadcast-image-builder#4]
The Raspberry Pi zero processing power is limited.  The two way communication program that allows synchronous control of wfb and other configurable options is only utilized prior to flight.  

Perhaps rc channel 24 could be configured to enable or disable this feature.  It could reduce CPU usage 10-20%.

**Comment by user1321** [comment]
Solved in latest build of current tree.
Please, open new issue in case of bugs.
